### PR TITLE
Added Git & GCS Account Registration plugins for google accounts

### PR DESCRIPTION
**Pull request by kirangodishala**
Added Git Account Registration plugin for google accounts

### CODE REVIEW

**Comment by mattgogerly** [comment]
Not sure if I'm missing something obvious here, but isn't this functionally equivalent to what the Armory credentials plugin does also?

Is there scope for OpsMx and Armory to standardise on a single plugin rather than maintain different plugins for different providers?

@link108

**Comment by kirangodishala** [comment]
@mattgogerly - could you provide the link to "Armory credentials plugin".  I thought this is the official repo where community would share the plugins. If there are multiple places, chances are that we duplicate the efforts.

**Comment by link108** [comment]
@kirangodishala here's a link: https://github.com/armory/spinnaker-credentials-plugin
I think we should be able to move the spinnaker-credentials-plugin to the OSS Plugins organization (https://github.com/spinnaker-plugins/), I'll check internally before making that change 👍  Hopefully that should make it easier to collaborate

**Comment by kirangodishala** [comment]
Thanks @link108. Credentials plugin is implemented with credentials accessed through a GET call to the source. We have implemented something similar for google accounts but with different sources - one with Git as a source and other is GCS. @mattgogerly - Can we add all the three plugins here first until we come up with a possible single plugin for all kinds of sources/protocols for external accounts?

**Comment by link108** [comment]
That sounds good to me 👍

**Review by link108 — APPROVED** [review]

**Comment by kirangodishala** [comment]
Thank you @link108. @mattgogerly - will you be able to merge the PR?

**Comment by kirangodishala** [comment]
@mattgogerly - can you please merge the PR?

**Comment by kirangodishala** [comment]
@mattgogerly @link108 - can one of you please merge this PR?

**Comment by kirangodishala** [comment]
@mattgogerly @link108 - Not sure if you are not able to merge the PR or have any objections to the merger but the PR is waiting for a long time. Could you please respond in any case?

**Comment by link108** [comment]
Hey @kirangodishala, happy to merge this 👍  thank you for the submission

**Pull request merged**
